echo "right_left"
rm part_1_pertubations/right_left/*
echo "left_right"
rm part_1_pertubations/left_right/*
echo "up_down"
rm part_1_pertubations/up_down/*
echo "down_up"
rm part_1_pertubations/down_up/*
echo "no_yes"
rm part_1_pertubations/no_yes/*
echo "yes_no"
rm part_1_pertubations/yes_no/*
echo "on_off"
rm part_1_pertubations/on_off/*
echo "off_on"
rm part_1_pertubations/off_on/*
echo "go_stop"
rm part_1_pertubations/go_stop/*
echo "stop_go"
rm part_1_pertubations/stop_go/*
